version: "3"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - data-db:/var/lib/postgresql/data
      - ./sql_queries/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
    ports:
      - 5433:5432
    container_name: postgres_db
volumes:
  data-db:  
